# Generated by Django 4.1.7 on 2023-04-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_options_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='category',
            field=models.CharField(default='null', max_length=266),
            preserve_default=False,
        ),
    ]
