# Generated by Django 4.1.7 on 2023-04-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_proxy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='category',
            field=models.CharField(default='Mobile', max_length=266),
            preserve_default=False,
        ),
    ]
